name: 27121_test

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:
        run: echo "Hello, world!"
        
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y make
