name: 27121_test

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y make
      
      - name: Create error file
        run: |
          if sudo apt update && sudo apt install -y build-essential make; then
            echo "OK" > napaka.txt
          else
            echo "Napaka" > napaka.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: error-log
          path: napaka.txt

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - name: Download artifact
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: error-log
      - name: Test
        run: ls -R
