name: 27121_deploy

on:
  workflow_run:
    workflows: ["27121_test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag nejcmiholicferi/testni_docker:latest

      - name: Push Docker image to DockerHub
        run: |
          docker push nejcmiholicferi/testni_docker:latest
