name: 27121_test

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
		      sudo apt-get install -y build-essential
          sudo apt install -y make

      - name: Save error log as artifact
        if: failure()
        run: echo "Napaka pri nastavlanju okolja." > error.txt
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: error-log
          path: error.txt

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - uses: actions/checkout@v2
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: error-log
          path: .

      - name: Check error log
        if: always()
        run: |
          if [ -f "error.txt" ]; then
            echo "Napaka pri nastavlanju okolja."
            exit 1
          else
            echo "Okolje uspesno nastavljeno."
          fi

      - name: Run tests
        if: success()
        run: |
          make all
		      ./demo_gcc
