name: 27121_test

on:
  push:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up environment
        run: |
          echo "123" | sudo -S -v
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y make
      
      - name: Create error file
        run: |
          if sudo apt update && sudo apt install -y build-essential make docker; then
            echo "OK" > napaka.txt
          else
            echo "Napaka" > napaka.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: error-log
          path: napaka.txt

  run_tests:
    runs-on: self-hosted
    needs: setup_environment
    steps:
      - name: Download artifact
        if: always()
        uses: actions/download-artifact@v2
        with:
          name: error-log

      - name: Check error status
        run: |
          error_status=$(cat napaka.txt)
          if [ "$error_status" = "OK" ]; then
            echo "Okolje ustvarjeno uspesno."
          else
            echo "Napaka pri ustvarjanju okolja."
            exit 1
          fi

      - name: Run app
        run: |
          make
          ./demo_gcc
