name: 27121_deploy

on:
  workflow_run:
    workflows: ["27121_test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          chmod +x .github/scripts/zapakiraj_27121.sh
          .github/scripts/zapakiraj_27121.sh
